# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[30,)" #mandatory (28 is current forge version)
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="bronze_age" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Bronze Age" #mandatory
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
authors="Yanny" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Bronze Age
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bronze_age]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bronze_age]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.bronze_age]]
    modId="ages_api"
    mandatory=true
    versionRange="[1.0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bronze_age]]
    modId="stone_age"
    mandatory=true
    versionRange="[1.0.5,)"
    ordering="NONE"
    side="BOTH"
